"""Make skill_id non-nullable

Revision ID: 4653cf4cd6ae
Revises: bcf07d6aa607
Create Date: 2025-04-15 08:14:11.136049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4653cf4cd6ae'
down_revision: Union[str, None] = 'bcf07d6aa607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proficiencies', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('proficiencies', 'skill_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proficiencies', 'skill_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('proficiencies', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
