"""Add target_user_id and relationships to Shoutout

Revision ID: bcf07d6aa607
Revises: 477874b15bca
Create Date: 2025-04-13 20:37:43.433895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf07d6aa607'
down_revision: Union[str, None] = '477874b15bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shoutouts', sa.Column('target_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shoutouts', 'users', ['target_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shoutouts', type_='foreignkey')
    op.drop_column('shoutouts', 'target_user_id')
    # ### end Alembic commands ###
